title = "TOML Example"

[general]
port = 8080

[scheduler]
timezone = "Europe/Kiev"
# Scheduler running interval, in cron format (with seconds)
# Examples: 
#   "p * * * * *" - With random period at seconds (p - period)
#   "0 s * * * *" - At random minute every hour (s strict)
#   "0 30 * * * *"  - Every hour on the half hour
#   "@hourly" - Every hour
#   "@every 1h30m" - Every hour thirty
#   "0 */2 * * mon-fri" - Every two hours from Monday to Friday
#
#   "random" for random next run time
crontime = "0 * * * * *"

[killer]
# Only pods with this label will be killed
# list of rules
selector = "destiny in (doomed)"
#If this is true - match_label will be ignored and all pods 
# with respectin go while/black lists may be killed
match_all = false
# If allow - all nodes except blacklist can be killed, ignore whitelist
# If deny - only pods in whitelist can be killed, ignore blacklist
namespace_deny_policy = true # default value will be deny
namespace_list = ["kube-system"]
# in seconds
retry_interval = 60





